# General settings
generate_video: true                         # Generate frame-based video
stop_early: false                             # stop after a few frames for debugging
render_roi: true                             # Render only a region of interest (ROI) around the ball to speed up rendering
roi_size: 100                                # Size of the ROI in pixels (only used if render_roi is true)

# Paths
dataset_path: "/data/lkolmar/datasets/test/" # Path to the dataset directory

# Spin settings
initial_orientation: [0.0, 0.0, 0.0]         # Initial orientation of the ball in [x, y, z] in axis-angle representation
spin_axis: [2.0, 0.0, 0.0]                   # Axis of rotation in [x, y, z]
total_rotations: 20.0                        # Total number of rotations to perform (rps is set implicitly by the simulation time)

# Trajectory setting
ball_start: [0.0, -0.45, 0.0]                # Starting position of the ball in [m, m, m]
ball_end: [0.0, 0.45, 0.0]                   # Ending position of the ball in [m, m, m]
scale_start: 2.3                             # Scale of the ball at the start position
scale_end: 2.3                               # Scale of the ball at the end position

# simulation settings
total_frames: 600                            # Total number of frames to simulate
simulation_time: 450000                      # Simulation time in microseconds (1,000,000 us = 1 s = 1,000 milliseconds)
video_fps: 30                                # Frames per second for the video
simulation_samples: 64                       # Number of samples per frame for the simulation
ball_name: "Sphere"                          # Name of the ball object in Blender

# camera settings
resolution_x: 1280                           # Horizontal resolution of the camera in pixels
resolution_y: 720                            # Vertical resolution of the camera in pixels
resolution_percentage: 100                   # Percentage of the resolution to use (100% = full resolution
focal_length: 9.0                            # Focal length of the camera in [mm]
pixel_pitch: 0.0075                          # Pixel pitch of the camera in [mm]

# event camera settings
th_pos: 0.05                                 # on threshold
th_neg: 0.05                                 # off threshold
th_n: 0.02                                   # noise threshold
lat: 150                                     # latency
tau: 200                                     # time constant
jit: 120                                     # jitter
bgn: 0.001                                   # background noise
ref_period: 10                               # ref-time of the event camera