""" Simulator for generating synthetic event data of a spinning ball

    This file provides a class to use the IEBCS part of the simulation pipeline
    As input, it needs a config file (e.g. config/default.yaml) which specifies the parameters of the simulation (e.g. trajectory, camera settings, etc.)
    Second input is a folder with all the images generated by the blender part of the pipeline which should be simulated to event-data

    This file uses techniques and libraries by IEBCS https://github.com/neuromorphicsystems/IEBCS
"""
import cv2
import yaml
import os
from tqdm import tqdm
import numpy as np
import pandas as pd
import glob
import sys
sys.path.append("IEBCS")
sys.path.append("utils")
from event_buffer import EventBuffer
from dvs_sensor import DvsSensor
from event_display import EventDisplay
from arbiter import SynchronousArbiter, BottleNeckArbiter, RowArbiter
import rotations



class EventSimulator:
    """ Class for simulating event data from a sequence of images. """

    def __init__(self, config):
        """ Initialize the simulator with the given configuration. """
        self.config = config
        self.set_config(config)
        self.calculate_fps()
        
    
    def set_config(self, config):
        """ Set the configuration for the simulator. """
        self.config = config
        
        # paths
        self.dataset_path = config['dataset_path']
        self.tmp_path = config['tmp_path']
        self.output_path = config['output_path']
        self.scene_path = config['scene_path']
        self.coords_path = config['coords_path']
        self.metadata_path = config['metadata_path']
        self.gt_path = config['gt_path']

        # settings
        self.stop_early = config['stop_early']

        # positional settings
        o = config["initial_orientation"]
        self.initial_orientation = rotations.Rotation()
        self.initial_orientation.set_axis(o[0], o[1], o[2])
        self.ball_start = config["ball_start"]
        self.ball_end = config["ball_end"]
        self.ball_scale_start = config["scale_start"]
        self.ball_scale_end = config["scale_end"]

        # spin-settings
        self.spin_axis = config["spin_axis"]
        self.spin = rotations.Rotation()
        self.spin.set_axis_np(np.array(self.spin_axis))
        self.total_rotations = config["total_rotations"]

        # resolution and video settings
        self.resolution_x = config["resolution_x"]
        self.resolution_y = config["resolution_y"]
        self.resolution_precentage = config["resolution_percentage"]
        self.focal_length = config["focal_length"]
        self.pixel_pitch = config["pixel_pitch"]
        self.total_frames = config["total_frames"]
        self.simulation_time = config["simulation_time"]
        self.video_fps = config["video_fps"]
        self.simulation_samples = config["simulation_samples"]
        self.ball_name = config["ball_name"]

        # event-camera settings
        self.th_pos = config["th_pos"]
        self.th_neg = config["th_neg"]
        self.th_n = config["th_n"]
        self.lat = config["lat"]
        self.tau = config["tau"]
        self.jit = config["jit"]
        self.bgn = config["bgn"]
        self.ref_period = config["ref_period"]


    def calculate_fps(self):
        """ Calculate the frames per second for the simulation. 
            This is based on the settings for total frames and simulation time, which are set in the config file.       
        """
        self.video_length = self.simulation_time / 1000000.0  # convert microseconds to seconds
        self.fps = int(self.total_frames / self.video_length)


    def simulate(self):
        """ Simulate the event data from the sequence of images. """
        
        # initialize dvs sensor
        dvs = DvsSensor("MySensor")
        # TODO: maybe fix noise numbers
        bgnp = self.bgn
        bgnn = self.bgn
        time = 0
        dt = self.simulation_time / self.total_frames # time per frame in microseconds
        print(f"Caution, maybe error is introduced by cutting dt from {dt:.4f} to {int(dt)} microseconds")
        dt = int(dt)
        dvs.initCamera(self.resolution_x, self.resolution_y, lat=self.lat, jit=self.jit, ref=self.ref_period, tau=self.tau, th_pos=self.th_pos, th_neg=self.th_neg, th_noise=self.th_n, bgnp=bgnp, bgnn=bgnn)

        dvs.init_bgn_hist(self.dataset_path + f"noise/noise_pos_161lux.npy", self.dataset_path + f"noise/noise_neg_161lux.npy")

        # get image paths
        pattern = os.path.join(self.tmp_path, "frame_*.png")
        image_paths = sorted(glob.glob(pattern))
        im = cv2.imread(image_paths[0])

        # Convert the image from uint8, such that 255 = 1e4, representing 10 klux
        im = cv2.cvtColor(im, cv2.COLOR_RGB2LUV)[:, :, 0] / 255.0 * 1e4

        dvs.init_image(im)

        ev_full = EventBuffer(1)
        ea = SynchronousArbiter(0.1, time, im.shape[0])

        render_timesurface = 1
        ed = EventDisplay("Events", self.resolution_x, self.resolution_y, dt, render_timesurface)

        for i in tqdm(range(1, len(image_paths)), desc="Simulating events"):
            im = cv2.imread(image_paths[i])
            im = cv2.cvtColor(im, cv2.COLOR_RGB2LUV)[:, :, 0] / 255.0 * 1e4
            ev = dvs.update(im, dt)
            ed.update(ev, dt)
            ev_full.increase_ev(ev)

        biases = np.array([self.th_pos, self.th_neg, self.th_n, self.lat, self.tau, self.jit, self.bgn, self.ref_period])
        ev_full.save_hdf5(self.output_path + "events.hdf5", bias=biases, width=self.resolution_x, height=self.resolution_y)

    def run_simulation(self):
        """ Run the entire simulation pipeline. 
        
            Wrapper to stay consistent with the blender simulator and the legacy code
        """
        self.simulate()


if __name__ == "__main__":
    # load config
    with open("../config/default.yaml", "r") as f:
        config = yaml.safe_load(f)

    # create simulator and run
    simulator = EventSimulator(config)
    simulator.simulate()